### ISSUE TITLE
Integrate frontend styling feedback

### ISSUE THREAD

**Issue by factoidforrest** [lunasec-io/lunasec#450]
# Gonna leave these recommendations here for both of us to reference in the future:

## Global
- Sidebar headings should be more distinct (uppercase? larger?)
- Breadcrumbs should be smaller
- Active vs inactive link colors should be consistent (sidebar active color is the same as the main content's inactive color)
- Dark mode slider needs to be overhauled
- Indentation in sidebar can be decreased to save space
- Adjust text sizing to use "clamp()" (`font-size: clamp(3.5rem 6.5vw 6rem);`, works better on ultrawide monitors) 
- Icons are not aligned with text's horizontal axis

## Project View
- Tab navigation in main content is inconsistent with the overall style of the UI
- "Click here" icon and text need better spacing

## Vulnerabilities View
- Fields and dropdowns should be consistently sized
- ~~Move user settings and dark mode slider to bottom of sidebar for space conservation~~ 
  - (We need to stick with a somewhat similar UX for what users expect, but maybe moving the dark mode slider to the Footer makes sense?)
- Move breadcrumbs to bottom of canvas for further space conservation
- ~~Consider adding placeholder after "Project Access Tokens" for when no content is available to be displayed~~ (likely out of date with the new pane)
- Typo: "drop-and-drop" instead of "drag-and-drop"
- User settings dropdown animation is probably too slow

## CSS Changes to reference
```css
// I'd recommend creating these variables for consistency
$color-link-active: #e9ecef;
$color-link-inactive: #adb5bd;
$color-background-active: #3F80EA;
$color-background-hover: $gray-100;

// Apply inactive color to sidebar links by default

a.sidebar-link {
color: $color-link-inactive;

  // Align icon with text baseline instead of descender, reduce space between icon and link text
  svg {
    margin-right: 0.5rem;
    margin-bottom: 0.075rem;
  }
}

// Apply link active color and changes active background color
a.sidebar-link-active {
font-weight: 500;
color: $color-link-active;
background-color: $color-background-active;

  // Applies background color to sidebar link hover
  &:hover {
    background-color: $color-background-hover;
  }
}

// Changes sidebar header styling to better differentiate from links
li.sidebar-header {
  font-size: 0.75rem;
  text-transform: uppercase;
  letter-spacing: 0.5rem;
  font-weight: 500;
}

// Aligns chevron when expanded
.sidebar [aria-expanded=true]:before, .sidebar [data-bs-toggle=collapse]:not(.collapsed):before {
  top:50%;
}
```
